### PR TITLE
Added support for private docker registries with basic auth or no auth, and improvements for token based authentication

### PR DESCRIPTION
**Pull request by rystaf**
This fixes the "Check for updates" button not working for images from private docker registries that don't use Bearer tokens for authentication. I tested this using the DockerRegistry container from Community Applications and Traefik providing the basic auth.

### CODE REVIEW

**Comment by bergware** [comment]
I did a quick test to see if regular registry downloads still work, this seems okay.
Did you test this against the regular registy too?

One request: can you comment out the debug statement (I presume you used it for troubleshooting)

**Comment by rystaf** [comment]
I tested it with public images on docker hub, but I did not test private docker hub images or public images on 3rd party registries that use bearer tokens. Turns out the original code did not work for me  at all. I just pushed a commit that fixes this. I tested it with a private docker hub image and a public image at dock.mau.dev/maubot/maubot. Also removed those debug calls.

**Comment by SquareMesh** [comment]
@rystaf @bergware Just feedback to let you know that this fix worked for me.  I was previously encountering the Not Available error.  My private docker registers sits behind SSL (LetsEncrypt docker) and this fix works to allow changes to be detected and allow upgrade to be applied.  I have other dockers, some based on Unraid templates and some direct from docker hub public images no errors occurring.   Thanks for the fix.  Will monitor and report if any surprise issues occur.

**Comment by SquareMesh** [comment]
Hi @limetech,

Any chance this can make next release?  Since applying fix locally it has been working with existing docker images aswell as private docker.

cc @rystaf @bergware

**Comment by SquareMesh** [comment]
Hi @bergware ,

Sorry to hassle, just wondering if you are considering this for the next release?  I'm continuing to use the changes made by this pull request in my system and fix appears to be working for both private docker and public dockers.  Is there any further tests or changes you are looking for?  Let me know if I can assist with further testing.

Apologies for questions, just keen to see this progress.

cc @rystaf, @limetech

**Pull request merged**
