### PR TITLE
Add per DIMM information toggle

### PR DESCRIPTION
**Pull request by realies**
Hidden by default and showing when **Memory** is clicked.

image

### CODE REVIEW

**Comment by bergware** [comment]
Two things to address/correct.
1. Skip empty slots
2. Ident the text like all other entries

image

**Comment by realies** [comment]
Maybe the modal window should also be wider to accommodate for the long text.

**Comment by ljm42** [comment]
Hey @realies check out the "Dynamix System Information" plugin.  It adds a "more" button to the "info" popup that gives this detail and quite a bit more.

**Comment by bergware** [comment]
What is the significance of the third entry? When removed it will fit the window.

**Comment by realies** [comment]
@ljm42 thought the system information modal can benefit from some aggregated memory info.
@bergware f50650a adds `Skip empty slots, Ident the text like all other entries`. Row width depends on the string lengths per line. Some UI magix may guarantee they are not going to overflow.

**Pull request merged**
