### PR TITLE
Fixed diagnostics errors when array was never started

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by limetech** [comment]
I'll merge this PR but what is the case where diags are gathered and those ini files are not present?

**Comment by bergware** [comment]
When the server is started but not the array (autostart = no).

**Comment by limetech** [comment]
I was wondering if there was a bug report or other report of this issue because even with autostart set to No, those ini files should still have been generated.

**Comment by bergware** [comment]
I guess this is one of those edge cases, which are not really fully examined

**Comment by ljm42** [comment]
Here is the bug report: https://forums.unraid.net/bug-reports/prereleases/680-rc5-command-line-diagnostics-throws-errors-r714/

**Comment by limetech** [comment]
Ok the one missing is 'diskload.ini' - that makes sense.

**Pull request merged**
