### PR TITLE
CPU Isolation: Prevent PHP error if no CPUs isolated

### PR DESCRIPTION
**Pull request by Squidly271**

### CODE REVIEW

**Comment by bergware** [comment]
Yeah, I overlooked some initialization.
$isol is actually a string, better to set as an empty string

**Comment by Squidly271** [comment]
> $isol is actually a string, better to set as an empty string. 

Technicality.  I thought about that originally setting it to be "", decided that it didn't matter either way and just deleted the line.  But, have updated it accordingly

**Comment by bergware** [comment]
I believe it is okay, but for semantics it is clearer/neater to initialize $isolcpus as an empty array. As you initially did.

**Comment by Squidly271** [comment]
As you wish.  But, it did work as is.  Different styles.

**Comment by bergware** [comment]
PERFECT :)

**Comment by Squidly271** [comment]
Yes, coding style is now "Dutchified"

**Comment by bergware** [comment]
Yeah, we like to be on top of things (or it is perhaps we are just tall people)

**Comment by Squidly271** [comment]
https://i.redd.it/tvxqbdux6uqz.jpg

**Comment by Squidly271** [comment]
[https://i.redd.it/tvxqbdux6uqz.jpg](url)

**Comment by Squidly271** [comment]
image

**Comment by bergware** [comment]
We wear the wrong (wooden) shoes ...

**Comment by Squidly271** [comment]
Gotta say though, that out of all the caricatures, the Canadian is the only one that looks cool :)

**Pull request merged**
