### PR TITLE
Multi-language support

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by bergware** [comment]
Please revert Merge pull request #626 from Squidly271/patch-7

It conflicts with my changes.

**Comment by Squidly271** [comment]
Then you have to incorporate my PR into yours.  You cannot allow some one with malicious intent to post say a Russian translation that includes code in his translations.  Big security issue.

**Comment by bergware** [comment]
I don't see a security risk. You can not execute code.
I tried to inject javascript in the text file, and it simply becomes text (what I expected to happen).

To convince me you have to show proof.

**Comment by Squidly271** [comment]
Just because something shouldn't be there, doesn't mean someone won't put it there.

Prior to my PR,  tossing this into plugins.txt (and of course deleting plugins.dot)

`Author='Auteur<script>alert();</script>'
`
would display an alert whenever going to the Plugins Tab.  After the change, no alert is displayed.

**Comment by bergware** [comment]
Ok, you convinced me :)
I added security, based on your proposal.

**Pull request merged**
