### PR TITLE
Add vmxnet3 and e1000 into available NICs for VMs

### PR DESCRIPTION
**Pull request by SimonFair**

### CODE REVIEW

**Comment by bergware** [comment]
A couple of things with your PR, which prevents it from pulling

1. It alters the default choice (virtio-net), new choices must be at the end of the list
2. New choices should also be made available in the template used for adding network interfaces (user clicks on the + button)
3. New choices should also be made available for the ELEC templates

**Comment by Squidly271** [comment]
> New choices should also be made available for the ELEC templates

Maybe it's time to remove those altogether?  They're 2 major versions behind

**Comment by SimonFair** [comment]
> A couple of things with your PR, which prevents it from pulling
> 
> 1. It alters the default choice (virtio-net), new choices must be at the end of the list
> 2. New choices should also be made available in the template used for adding network interfaces (user clicks on the + button)
> 3. New choices should also be made available for the ELEC templates

Thanks for feedback will review.

**Comment by bergware** [comment]
> Maybe it's time to remove those altogether?

AFAIK there are people using these templates, albeit not many.

**Comment by SimonFair** [comment]
> > Maybe it's time to remove those altogether?
> 
> AFAIK there are people using these templates, albeit not many.

I didnt change those ones as people would be unlikely to change from defaults.

Revised order and added 2nd NIC options.

**Comment by SimonFair** [comment]
Defaults are not set by the list order, should it be alphabetical in the list?

**Comment by bergware** [comment]
I prefer as you have done in your last PR (no need to make changes).

virtio-net should be the first choice with virtio as second choice, these are the recommended general choices.

**Comment by SimonFair** [comment]
> I prefer as you have done in your last PR (no need to make changes).
> 
> virtio-net should be the first choice with virtio as second choice, these are the recommended general choices.

Ok thanks, I think the ELEC should be left with the virtio only NICs, as they OS works with them.

**Pull request merged**
