### PR TITLE
Changes for Mover Status

### PR DESCRIPTION
**Pull request by SimonFair**
Please find changes for Mover Status using NCHAN for review.

Changes to mover script as before let me know if you need me to resend mover script via forum PM.

if changes to move command are available for me to test let me know and I can make the necessary changes to the mover script.

Let me know if there is a better way to tell main page mover is not running.

### CODE REVIEW

**Comment by SimonFair** [comment]
Move script is here => https://gist.github.com/SimonFair/91d54c983a8c9b09c0d803baa25f01ac

**Comment by bergware** [comment]
Looks good :)
Checking mover.pid is okay.

Can you change the indirect file reference to a direct reference
'/usr/local/emhttp/state/mover.ini'  -> "$varroot/mover.ini"

And add translation:
$data[] = _('Error')
$data[] = _('Error')

Thx

**Comment by bergware** [comment]
One more thing
You need to make **mover_list** executable on github by default it has 0644 permissions.

**Comment by SimonFair** [comment]
> git commit -m "Make mover_list executable"

Thanks for the feedback, changes actioned.

**Comment by limetech** [comment]
I plan to merge this but I need to complete my own review first, thank you for the code changes!

**Comment by bergware** [comment]
rc3 has a new detection method for background operations like mover, parity and btrfs.
Your latest changes introduce a duplicate function for the mover. Better to align this with the new rc3 implementation.

**Comment by SimonFair** [comment]
> rc3 has a new detection method for background operations like mover, parity and btrfs. Your latest changes introduce a duplicate function for the mover. Better to align this with the new rc3 implementation.

Ok thanks we take a look at rc3 changes, was just trying to resolve the conflict.

**Comment by bergware** [comment]
Yes, probably best to wait for rc3 and see how your code can be adapted to match the latest implementation.

**Pull request closed without merging**
