### PR TITLE
Multi-language Support

### PR DESCRIPTION
**Pull request by Squidly271**
Remove any translations that attempt to inject code into the OS

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
Does this protect against attack like so?

```
<b onmouseover=alert(‘XSS testing!‘)></b>
```

**Comment by Squidly271** [comment]
Good point.  Thanks.  Now I've got to think about this mainly with regards to the application feed as formatting is allowed within descriptions which significantly complicates the situation.  And formatting is also allowed (and necessary) within translations

**Comment by OmgImAlexis** [comment]
What I've seen is using something like this `_t(`The {0} {1} is ready for download`, red, 'ball')` for the translations where they need formatting and such.

Is there any other formatting stuff you'd need?

**Comment by Squidly271** [comment]
Goes beyond that.  This isn't about the phrase to be translated.  Its about what the translated text is.

**Comment by OmgImAlexis** [comment]
Whatever way we work it out it needs to be compatible with the way we’re going todo this in vue too.

**Comment by OmgImAlexis** [comment]
Might be worth looking into http://htmlpurifier.org

**Pull request merged**
