### PR TITLE
Block referrals to 3rd Party Sites

### PR DESCRIPTION
**Pull request by Squidly271**

### CODE REVIEW

**Comment by ljm42** [comment]
Ideally, all of the files that contain:
```
<meta name="robots" content="noindex, nofollow"> 
<meta http-equiv="Content-Security-Policy" content="block-all-mixed-content">
```
would get this header too:
`  <meta name="referrer" content="same-origin">`

See https://github.com/limetech/webgui/pull/523/files

**Comment by Squidly271** [comment]
Go ahead.  I'll withdraw this PR in lieu of yours

**Comment by Squidly271** [comment]
My primary concern was with pages and links that LT has no control over.  Support / Project / Registry pages, and the donate links authors put on their settings page, which this PR does cover (Mainly because I'm the one who pushed to have all those links there in the first place).

**Comment by ljm42** [comment]
OK I've submitted #588 which adds the header to all files. Just to be sure :)

**Comment by Squidly271** [comment]
Thanks   closing

**Pull request closed without merging**
