### PR TITLE
This code checks for a theme-specific JS file

### PR DESCRIPTION
**Pull request by webprogrammingsolutions**
And it includes it in the page render if it exists.

Gives theme author opportunity to enhance UI//UX.

### CODE REVIEW

**Comment by bergware** [comment]
Any example where this is used?

**Comment by webprogrammingsolutions** [comment]
Not yet. Working on a new Material Design theme and would be nice to have a re-sizeable sidebar which would require some custom jQuery.

**Comment by bergware** [comment]
There exist already a possiblity to insert (conditional) javascript code.
You need to create a page file, e.g. /plugins/myplugin/MoreJS.page
The content of MoreJS.page looks like this

Menu="Buttons"
Cond="$display['theme']=='azure'"
---
<script>
...
...
</script>

**Comment by webprogrammingsolutions** [comment]
ok, I can work with that. The code I suggested may still be helpful down the road. Do you have a roadmap for anything theme related in unRAID? Or are things staying as-is for the forseeable future?

**Comment by bergware** [comment]
I don't see the core framework of the GUI changing in the forseeable future.
E.g. the function I was referring to, exists since the introduction of Unraid v6.

**Pull request closed without merging**
