### PR TITLE
Keep GUI in sync with diagnostics spinning up drives

### PR DESCRIPTION
**Pull request by Squidly271**
If there's a better way of doing it, feel free to not merge

https://forums.unraid.net/bug-reports/stable-releases/diagnostics-spins-up-drives-but-show-down-in-array-r1363/

### CODE REVIEW

**Comment by limetech** [comment]
Instead of looping over disks you can use

cmdSpinupAll=apply

api call.

**Comment by Squidly271** [comment]
Thanks.  As an aside, that's not how the GUI works.  It calls ToggleState on spin up / spin up all and loops through the drives.

**Comment by limetech** [comment]
> As an aside, that's not how the GUI works. It calls ToggleState.php on spin up / spin down all and loops through the drives, hence the original coding.

Looking at code looks like ToggleState.php does take into account spin-up/down All and invoke either cmdSpinupAll or cmdSpindownAll.  For a group this really should be using spin-up groups now since that code works for array and pools as of 6.9 release.

**Comment by Squidly271** [comment]
I traced the code, and it always seems to spin individually.  But, in retrospect that may be because on the array the spinup only spins up the array, etc.

**Comment by limetech** [comment]
cmSpinupAll will spin up all devices: those in array, pools, and unassigned.

**Comment by Squidly271** [comment]
Looks like this was fixed via different manner in 6.9.2  closing

**Pull request closed without merging**
