### PR TITLE
Parity operation enhancements

### PR DESCRIPTION
**Pull request by bergware**
- Separate Parity-Sync and Data-Rebuild as individual actions
- Add parity operation action to history view
- Correct calculations for data-rebuild smaller than parity
- Add disk clear action
- Use Nchan updates for copying/clearing progress
- CSS adjustment in SMART attributes
- Show additional buttons in Array Stopped state
- Textual enhancements
- Sync Dashboard view with Main view

### CODE REVIEW

**Comment by bergware** [comment]
Please wait with merge, making more adjustments/corrections.

**Comment by OmgImAlexis** [comment]
> Please wait with merge, making more adjustments/corrections.

You can change this to a draft PR which will prevent merging and then change it back once done.

**Comment by bergware** [comment]
Ok, thanks for the tip.
PR is ready now

**Comment by bergware** [comment]
Encountered a minor issue which needs to be resolved

**Comment by bergware** [comment]
Ok, found the problem. It is related to the parity check tuning plugin, which isn't compatible with these latest additions.

**Comment by limetech** [comment]
wow! nice work

**Pull request merged**
