### PR TITLE
Preserve reboot notices across GUI pages

### PR DESCRIPTION
**Pull request by Squidly271**
Currently reboot required from CPU isolation / VM settings do not preserve the warning across pages.

The PR will preserve those warnings across pages and cycle through them on a 10 second basis.

The other sections in the GUI that also require reboots to take effect are currently listed in the help text, and will slowly be retrofitted to this banner routine if/when this PR is accepted

See also https://forums.unraid.net/topic/79010-ca-api-for-plugin-update-checks/?tab=comments#comment-812897 (although currently the removeRebootNotice() in this PR hasn't been backported to CA as of yet)

### CODE REVIEW

**Comment by Squidly271** [comment]
Don't merge for 6.8.2 if it's imminent... more I want to do with it....

**Comment by limetech** [comment]
> Don't merge for 6.8.2 if it's imminent... more I want to do with it....

haha, didn't see this until after merging - oops

**Comment by limetech** [comment]
I reverted but don't see your PR there anymore :(
Obviously my github-kungfu need some refreshing...

**Comment by Squidly271** [comment]
After work slows down and I get over my cold I'll re-issue.

**Pull request merged**
