### PR TITLE
Restore Apply button to previous behavior

### PR DESCRIPTION
**Pull request by bergware**
+ little rewrite to PHP7 syntax

### CODE REVIEW

**Comment by Squidly271** [comment]
Picky, picky.  You can also save a lot of characters by switching all leading spaces to tabs (or at least being consistent between spaces on one file and tabs on another)

**Comment by bergware** [comment]
LOL. I like PHP7 coding style...

**Comment by Squidly271** [comment]
https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by eschultz** [comment]
@Squidly271 Funny scene, great TV show!

**Comment by bergware** [comment]
ROFL. I am with the lady all the way :)

**Comment by bergware** [comment]
If tabs is your preference, you would hate programming in python. They standardize on 4 spaces :)

**Comment by Squidly271** [comment]
Years ago I switched to tabs.  Memory was far more limited then.  Personally it doesn't bother me so much, but in an interpreted environment, execution speed is ever so slightly infinitesimally faster. 

Consistency though.  eg dockerMan/include/Events.php: tabs  Other files spaces (presumably the ones you've touched)

**Comment by bergware** [comment]
Once I couldn't resist and changed all the tabs to spaces, it created a small war with Tom and Eric.
So those files with tabs, I use tabs too to keep consistency, and consistency is a good rule for creating code, or that's what was taught me.

My first coding experience was at the time people talked about kilobytes, 64K max.

**Comment by limetech** [comment]
I use tab key that inserts spaces ;)
My rule 1: When changing someone's code, follow whatever style the original author used for their code.  If someone looks at the code they shouldn't be able to tell who wrote it based on the coding style.
Corollary 1 to rule 1: I won't change an entire file to match "my" style.
Corollary 2 to rule 1: But I don't give a crap if someone changes mine, learned long ago this battle is not worth fighting and sometimes their style is better!
My rule 2: Code should be easy for human to read first, not computer.

* It has happened that someone changed all spaces to tabs (or vice versa) and I objected - doesn't that violate my rule1/corollary2?  No because it wasn't the coding style change I objected to, it was the commit indicated over 300 files changed! and I didn't want to review every single one of them or take time to verify only change was whitespace.

**Comment by bergware** [comment]
LOL. I was shown a yellow (or was it red) card. Lesson learnt.

**Pull request merged**
