### PR TITLE
Change docker caching to private variables

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by limetech** [comment]
Man, you get any sleep?  Should I include this in 6.5.1-rc1?

**Comment by bergware** [comment]
I did have sleep, sure :)
Trying to get my corrections and ideas done before you publish 6.5.1rc, which has a short deadline !!

**Comment by bergware** [comment]
Ps. This latest PR has commented out the "security patch" of squid. Are we all in agreement to do this, if yes it can be uncommented.

**Comment by limetech** [comment]
I'm lost too.  There was a merge conflict with your PR so I reverted his (because I merged his first).  Then the PR got closed by github, not sure why.  So I manually added what I thought was the code change from his PR and pushed.

As for deadline: you know we are flexible.  In future just say, "Hey man that's a pretty tight deadline."  I wanted to get 6.5.1-rc1 out there mainly for security related changes (intel microcode, linux kernel, and curl CVE patch).

**Pull request merged**
