### PR TITLE
Spice html client in addition to VNC

### PR DESCRIPTION
**Pull request by SimonFair**
I have added support for Spice setup using the spice html client.

image

Template view spice.

image

Template view for VNC - Complete, reverted change to stop update of ports as now in GUI.
image

Menu, may add protocol i.e. (Spice) (VNC) : Complete

image

Spice console
image

Things to complete.

Port processing for Template view to allow update and support autoport option. Complete 

Currently functions exist with VNC name for models, keyboards, ports etc can these be aligned to be the same names as my new functions or do they need to remain for plugins that may be using?

Update spice.html to prompt for password if set. Currently you have to press the spice button to get the password : Complete(Simple Quote popup for now) Will add better options in future.

image

Test with a 2nd GPU installed. Complete, tested as 2nd GPU and only GPU with K4000.

Test on system using HTTPS for WebGUI: Complete

Features that can be added in future updates include USB Redirection with full client, not supported in HTML client.

### CODE REVIEW

**Comment by limetech** [comment]
This is awesome!  I'll have @eschultz review.

**Comment by SimonFair** [comment]
Added password form.

image

**Comment by SimonFair** [comment]
> This is awesome! I'll have @eschultz review.

Thank you.

**Comment by SimonFair** [comment]
Sorry @eschultz I have only completed the Custom template, and should not have included LibreELEC in the commits, but both this and OpenELEC will need to be reviewed for updates.

**Review by eschultz — APPROVED** [review]
LGTM. Thanks @SimonFair 🍺

**Comment by SimonFair** [comment]
> LGTM. Thanks @SimonFair 🍺

Is the plan to continue with ELEC templates?

**Comment by eschultz** [comment]
> Is the plan to continue with ELEC templates?

Yes. Would it be possible to flush out both ELEC templates in this PR? or we could accept the PR as-is and modify the ELEC templates after?

**Comment by SimonFair** [comment]
> > Is the plan to continue with ELEC templates?
> 
> Yes. Would it be possible to flush out both ELEC templates in this PR? or we could accept the PR as-is and modify the ELEC templates after?

I have update the ELEC templates, but having an issue with the hidden fields but they work if I dont hide them

Looks like ELEC templates are broken in 6.10 as network source is incorrect I have fixed that also but heed to see if I can fix hidden value before ready.

image

**Comment by SimonFair** [comment]
@eschultz Can see why the hidden fields dont work, are you have to review and let me know if you can see any thing for the Elec templates.

**Comment by SimonFair** [comment]
@eschultz I have fixed the selection on the templates and all 3 including the ELEC templates are now complete. Please can you review again.

**Comment by SimonFair** [comment]
@limetech @eschultz I will leave this as darft until you want to merge and you are happy with it.

**Pull request merged**
