### PR TITLE
Users: Display Password Strength

### PR DESCRIPTION
**Pull request by Squidly271**
Concept.  I fully expect @bergware to refine the styling

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
Doesn’t this add a false sense of security?

**Comment by Squidly271** [comment]
Gives people a clue of how weak their password is.  Pretty common nowadays to have this check.

**Comment by limetech** [comment]
Please translate that regex to English: what is this doing?

**Comment by OmgImAlexis** [comment]
Somewhat of an issue I've had in the past with "strength meters".

```
validatePassword('Should this long secure password comes up as medium just because it has no numbers and such in it')
```

**Comment by bergware** [comment]
Medium
"paid $10 dollar for this password with more than 8 characters"

Strong
"Password1#"

**Comment by Squidly271** [comment]
Thinking about it overnight I believe that we should limit this to just checking against the root password

**Comment by bergware** [comment]
If we are going to use this, I would make the rules for "medium" more stricter.
Just adding a uppercase letter isn't really that much more secure ... just saying!

**Comment by Squidly271** [comment]
Personally I don't think that's necessary.   Nobody ever suggests to make sure that your password is at least medium.   All suggestions everywhere is to create a strong one

**Comment by Squidly271** [comment]
And it's not just a capital letter.   password1 or password$ is also medium

**Comment by bergware** [comment]
So why do we use medium?

**Comment by Squidly271** [comment]
Because it's better than weak.   It's not like theres any rule enforced that the password has to be strong

**Comment by bergware** [comment]
So "password123" is better than "password" ;)

**Comment by Squidly271** [comment]
Touche

**Comment by bergware** [comment]
https://youtu.be/_JNGI1dI-e8

**Comment by limetech** [comment]
Amazing! That's the same combination on my luggage too!

**Comment by limetech** [comment]
Keypass has a "quality meter", examples:

image

image

image

**Comment by bergware** [comment]
@Squidly271 with your permission, I changed the password validation from regex to javascript "zxcvbn". From github:

zxcvbn is a password strength estimator inspired by password crackers. Through pattern matching and conservative estimation, it recognizes and weighs 30k common passwords, common names and surnames

It classifies passwords as worst, bad, weak, good and strong.

Entering "password123" as password gives

image

(for sharp eyes: I made a bar which grows with the length of the entered password and changes color depending on how "zxcvbn" rates the password strength)

**Comment by Squidly271** [comment]
That works for me.   Like stated in the OP this was a concept  didnt invest much time in it, but with where unraid is going something like this is needed on the root password.   Dont believe we need to put it on any users.

Closing this PR

**Comment by bergware** [comment]
I would leave that strength indicator for every user's password, to make the user more aware

**Comment by ljm42** [comment]
Thanks for starting this conversation @Squidly271 , this is a really good idea.  And wow @bergware , zxcvbn is a great find

**Comment by OmgImAlexis** [comment]
Since were adding this maybe we should also look at adding pwned password checking? There are a few js libs that interface with this. 

https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/

**Pull request closed without merging**
