### PR TITLE
Docker: Suppress error if no volumes present in template

### PR DESCRIPTION
**Pull request by Squidly271**

### CODE REVIEW

**Comment by bergware** [comment]
I am not sure this works:  **$ct['Volumes'] = is_array($ct['Volumes']) ?: [];**
In case the array exists it will be set as "true" which is returned by the "is_array" function.

**Comment by Squidly271** [comment]
Yeah you're right.  Weird thing though is that it worked lol  Fixed proper.  TY

**Comment by eschultz** [comment]
Thanks!

**Comment by bergware** [comment]
Just for fun (and own interest) I made a small test
```
$test = [1,2,3,4];
$test = is_array($test) ?: [];
echo print_r($test,true);
```
This sets $test = 1 (true) and the array content is lost

**Comment by Squidly271** [comment]
> This sets $test = 1 (true) and the array content is lost

Yeah, I was looking for PHP errors when I did the patch on my system. and a foreach (true as $xx) does not generate a warning / error, so missed the fact that I lost all the volumes on the page.  

I'm allowed to make a mistake once a year ;)

**Comment by bergware** [comment]
No worries, that's why we have safety nets aka code reviews ...

**Pull request merged**
