### PR TITLE
Use tooltipster for all title attributes

### PR DESCRIPTION
**Pull request by Squidly271**
Doesn't work though on titles for Unassigned Devices as they are generated after the page is loaded.

### CODE REVIEW

**Comment by limetech** [comment]
Where's an example of this being used?

**Comment by Squidly271** [comment]
Hover text on the icons on the right.  (log, etc)  Especially when the windows is less that 1920 and only icons display.  Basically just gets rid of any of the built-in browser hover text and switches it to tooltipster.  Up to you.  Doesn't worry me at all.


Andrew Zawadzki
Technical Trainer
Arrow Games / Bazaar & Novelty
Office: 800.387.7621 ext 246
Cell: 289.213.0130
Email: azawadzki@arrowgames.com<mailto:azawadzki@arrowgames.com>



________________________________

**Comment by bergware** [comment]
Personally I find tooltipster a bit "heavy" at least with the current (default?) styling. Is there a way to make it less prominent for the 'standard' tool tips?

**Comment by Squidly271** [comment]
lol.  That's the last time I reply to a github notification from work....  Nothing like having personal info present.

Personally, I hate the standard tooltips.  Admittedly they aren't used too much in stock unRaid.  I'll close the PR.

You can adjust the sizing etc for tooltipster taking the place of title elements, but I'm not going to invest the time in this.

**Comment by bergware** [comment]
Won't put it completely aside. If a "nicer" default style can be defined then tooltipster is still an option.
I'll keep it on my plate.

**Pull request closed without merging**
