### PR TITLE
dockerMan: Remove code for template repositories

### PR DESCRIPTION
**Pull request by Squidly271**
Don't hold up an RC over this

### CODE REVIEW

**Comment by bergware** [comment]
When you remove the download function, it will break the Docker update logic in the GUI.
We should leave that in.

**Comment by Squidly271** [comment]
Yup, there is a single instance where it's used that I missed within DockerTemplates.  Thanks

**Comment by bergware** [comment]
The function "downloadTemplates" is used by the GUI to retrieve the latest versions when clicking on "Check for Updates".
This won't work anymore after your PR, I believe.

I am not against code cleanup, but I think this one needs a bit more testing to understand the consequences.

**Comment by Squidly271** [comment]
Yes the GUI did call that routine.  Hence why it was deleted ln the original PR.  I did miss a reference in the background schedule (dockerupdate) after your first post

I've been running this code since 8/1 on a production server.  If you want to test it out yourself, then install it.

It doesn't need to be merged anytime soon as it is simply a cleanup and doesn't affect functionality at all.

**Comment by limetech** [comment]
Is this good to merge?

**Comment by Squidly271** [comment]
Leave it until @bergware tests it

**Comment by Squidly271** [comment]
Let's leave the code in for a while.   Closing this out.

**Pull request closed without merging**
