### PR TITLE
Diagnostics Update to #408

### PR DESCRIPTION
**Pull request by Squidly271**
More generalized.  Actually itemize which disks the share is stored on.

### CODE REVIEW

**Comment by limetech** [comment]
What's "/mnt/RecycleBin"?  That a mount point?  If so, what's mounted there?

**Comment by Squidly271** [comment]
On my system with the recyclebin plugin installed, that is present in /mnt  Contains (not surprisingly) the files that have been deleted.  Don't ask me why dmacias chose that location.  Simply wanted for the change to only pick up unRaid stock items.

**Comment by limetech** [comment]
If you look at this file:
https://github.com/limetech/webgui/blob/master/plugins/dynamix/include/Browse.php

On line 39 it uses 'getfattr' command to fetch Unraid-specific extended attribute called 'system.LOCATIONS' that lists all the disks that a share is present on.  You could use this extended attribute value in the diagnostics report.

For completeness: there is also 'system.LOCATION' which is valid for any file in Unraid user share file system that tells you what disk that file is located on.  We use this, eg, when a VM is started to pass the actual vdisk disk paths, so that I/O bypasses FUSE.

**Comment by Squidly271** [comment]
Updated

**Pull request merged**
