### PR TITLE
dockerMan: Download category lists

### PR DESCRIPTION
**Pull request by Squidly271**
Downloads Up To Date category lists if the following is true:

- Referrer to AddContainer page is NOT CA
- Template Authoring Mode is enabled
- Referrer to AddContainer is CA, but CA is not up to date (release currently pending)

Side note is that I noticed that the Tools Category wasn't exactly what specified on the categories, so have redefined it slightly by making it have two subcategories (System and Utilities).  AppFeed is handling this change automatically for existing templates.

### CODE REVIEW

**Comment by bergware** [comment]
What is the advantage of doing this?
It seems to me that as soon as CA has downloaded the list, it will always refer to the CA list.

**Comment by Squidly271** [comment]
Suggestion by Tom in PR #486 

Since CA is not included in Base OS, the system has to handle it not being installed, and even if CA is installed, no guarantee that a template author would have loaded CA first to populate the categories, so dockerMan has to download it regardless.

**Comment by limetech** [comment]
This change is not necessary for 6.7 'stable' release, correct?  (We could merge into 6.7 patch release or wait to integrate with 6.8?)

**Comment by Squidly271** [comment]
Fundamentally, it's a minor change in dockerMan.  It can wait until 6.8 (or 7.0 as categories don't change very often)

**Comment by limetech** [comment]
Are you putting this "Fix OS Update banner overhanging on Azure/Gray" in a separate PR?

**Comment by bergware** [comment]
Squid asked me to make the PR (I guess he has too many changes in his style sheets).
See my PR

**Comment by Squidly271** [comment]
Closing, as it is basically a PR for PR's sake, and really serves no purpose due to the infrequency of the problem which it solves

**Pull request closed without merging**
