### PR TITLE
Add in Support & Project Links to Docker Context Menus

### PR DESCRIPTION
**Pull request by Squidly271**
Every container installed via CA should already have the Support Link present (if installed post 6.2)
Majority of apps in CA also have a project link present (and passed to dockerMan), but thus far dockerMan hasn't saved that entry on user templates, so the Project link on the context menus will only appear for new containers added after the PR is approved.  (After published, I'll probably post a script to update everyone's user-templates with the appropriate Project URL's)

Additionally, dockerMan template authoring mode will also now support the most common CA xml entries (but nowhere near all) that template authors currently have to add manually to the generated xml file
untitled1

### CODE REVIEW

**Comment by Squidly271** [comment]
Sorry about the commit, followed by a revert and a revert of the revert.  Still learning GitHub.

**Comment by limetech** [comment]
This good to go?

**Comment by Squidly271** [comment]
If there's a problem, I can't find it

**Comment by Squidly271** [comment]
OK.  Found that IE doesn't like default parameters on functions.  Fixed

**Pull request merged**
