### PR TITLE
Multi-language support

### PR DESCRIPTION
**Pull request by Squidly271**
Language update checks were not working.

### CODE REVIEW

**Comment by Squidly271** [comment]
BTW @bergware, is the notice not translated for a reason other than the extra code required to get the current language?  I can add that in (same thing on plugincheck)

**Comment by bergware** [comment]
I did not add multi-language support in any of the scripts yet, but it's okay to do.
The translations probably need to go in "translations.txt" (a single source file).

**Comment by bergware** [comment]
Thanks for correcting the script, it was overlooked.

**Comment by Squidly271** [comment]
Put the translations into plugins.txt.  Made more sense to me, and once a plugin update appears I'll do the plugincheck script

**Comment by bergware** [comment]
The multi-language support at the beginning of the script needs to be revised a little

```
session_start();
$docroot = $docroot ?? $_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp';

require_once "$docroot/webGui/include/Wrappers.php";
require_once "$docroot/plugins/dynamix.plugin.manager/include/PluginHelpers.php";

$var     = parse_ini_file('/var/local/emhttp/var.ini');
$unraid  = parse_plugin_cfg('dynamix', true);

// Multi-language support
$_SESSION['locale'] = $unraid['display']['locale'];
$_SERVER['REQUEST_URI'] = "scripts";
require_once "$docroot/webGui/include/Translations.php";
```

**Comment by Squidly271** [comment]
Done.  I'll close the en_US PR and create a new file scripts.txt

**Comment by bergware** [comment]
The original conditional coding was onl;y done as a safety measure and to prevent potential errors.

Within a script the function _() doesn't exist, but since we do now "official" multi-language support by including translations.php, this checking is not needed and could be simplified.

**Comment by limetech** [comment]
good to go for next beta?

**Comment by Squidly271** [comment]
It works for me

**Comment by bergware** [comment]
> good to go for next beta?

Looks alright

**Pull request merged**
