### PR TITLE
Use timeout in command execution of diagnostics

### PR DESCRIPTION
**Pull request by bergware**
To prevent hanging of diagnostics, commands are killed after 30s.

### CODE REVIEW

**Comment by Squidly271** [comment]
Cool.  I can stop maintaining my autostart manager :)

**Comment by bergware** [comment]
I introduced some regression errors in Docker. Need to fix that :(

**Comment by limetech** [comment]
Looks like this is ready to rock 'n roll!  Merging...

**Comment by Squidly271** [comment]
Just a comment on docker CPU pinning.  I would like to see that if ALL cores are checked off, then dockerMan does NOT add any --cpuset-cpus to the docker run command.  (ie: if all cores are selected, then don't enter anything into the <CPUSet> tag at all.

My feeling is that users would wind up checking off all cores (when they don't have to), and if/when they upgrade their CPU, then they would be surprised that their containers are no longer running on all the possible cores without editing each container.  

Related, I would also prefer to see all cores checked off by default if nothing is entered into <CPUSet>  

Trouble is that this behaviour I'm proposing is opposite to the behavior of the VM manager where you have to select everything.  Up to @bergware

**Pull request merged**
