### PR TITLE
Add installed plugins & version to diagnostics

### PR DESCRIPTION
**Pull request by Squidly271**

### CODE REVIEW

**Comment by bergware** [comment]
I guess we can leave the '.plg' extention out in the list.

basename($plugin) ==> basename($plugin,'.plg')

**Comment by Squidly271** [comment]
I originally had instead of the filename the result of plugin name $plugin, but decided that the two were close enough to each other.

**Comment by bergware** [comment]
Haven't checked, but you're problably right. File name and plugin name are usually the same/similar.

**Comment by limetech** [comment]
Need to merge into 6.4.1 - are we good to go?

**Comment by Squidly271** [comment]
I think we are.  I reverted another commit that shouldn't have been included with this PR (unused icons)

**Pull request merged**
