### PR TITLE
feat(docker): process bash ANSI colors in web log display

### PR DESCRIPTION
**Pull request by nysos3**
This adds support for properly displaying the colors output by some docker containers' logs.

### CODE REVIEW

**Comment by bergware** [comment]
Do you have an example of a container which uses ANSI codes in its log?

**Comment by OmgImAlexis** [comment]
Can you please an example of how it looks on a white background as the standard is based on a black background and that may cause issues here.

**Comment by nysos3** [comment]
tdarr and tdarr_node both have ANSI codes in their log.

image

image

**Comment by limetech** [comment]
Merged, thank you!

**Pull request merged**
