### PR TITLE
Integrate CA's Plugin Helper

### PR DESCRIPTION
**Pull request by Squidly271**
Integrate CA's plugin update helper to the base OS.

Complete documentation here https://forums.unraid.net/topic/79010-ca-api-for-plugin-update-checks/

### CODE REVIEW

**Comment by bergware** [comment]
Can you make a small change in PluginAPI.php, instead of a "fixed" reference, make it programmable.

Original
require_once("/usr/local/emhttp/plugins/dynamix.plugin.manager/include/PluginHelpers.php");

New
$docroot = $docroot ?? $_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp';
require_once "$docroot/plugins/dynamix.plugin.manager/include/PluginHelpers.php";

note: "require_once" is not a function and the PHP preferred syntax is to use it without (), though it does work/is accepted when "require_once" is given a parameter (I guess because so many people don't know it)

**Comment by Squidly271** [comment]
If testing, ensure that CA version is greater than 2019.09.01a  Due to a logic error, the version included in CA was over-riding the version in this PR.

**Comment by limetech** [comment]
Is this good to go?

**Comment by Squidly271** [comment]
I dont see any problems with it

**Comment by bergware** [comment]
Looks good.

**Pull request merged**
