### PR TITLE
Task Plugins: Providing Ability to define Display_Name

### PR DESCRIPTION
**Pull request by dorgan**
Gives the ability to provide a Display_Name for when displaying task menu bar as having spaces in the file name seems to mess things up further.
Screen Shot 2020-05-02 at 9 17 59 AM
Screen Shot 2020-05-02 at 9 17 48 AM

### CODE REVIEW

**Comment by bergware** [comment]
Why are there two properties "Name" and "Display_Name"? Neither is used by Unraid.

A single property "Name" sounds more logical, and makes a very small 1 line change.

**Comment by dorgan** [comment]
@bergware isnt Name used for nesting of items in the menu, and is more of an ID, such as when its a tabbed interface or nesting different sections.  Thats my current understanding

**Comment by bergware** [comment]
Page nesting is done using the "Type" property.
E.g. Type="xmenu", tells the parser that this page has one or more "children" attached to it.

Page tabbing is controlled automatically, or can be forced using the "Tabs" property.

**Comment by bergware** [comment]
I propose you make your change like this

`echo "<a href='/$page' onclick='initab()'>"._($button['Name'] ?? $page)."</a></div>";`

Just a one line change with "$button['Name'] ??" inserted.
This allows you to overrule the automatic name generation for an item in the header by using the "Name" property in a page file.

**Comment by bergware** [comment]
Scratching my memory here.

In the pre-dynamix days (Unraid v5) there used to be a "Name" property, but I can't remember how it was exactly used.

**Comment by dorgan** [comment]
Maybe that's why I have it, there no official documentation so I've had to
reverse engineer alot.  I can make the proposed changes a little later.

**Comment by dorgan** [comment]
@bergware name Vs Name is very confusing of property, is still think Display_Name might be appropriate here, thoughts?

**Comment by bergware** [comment]
I don't think there is any confusion and "Name" is the most suitable solution.

When creating page files and setting the appropriate properties in the file, you won't have to take into consideration any of the internal properties (there are more internal properties).

**Comment by dorgan** [comment]
@bergware the current assignment for $page is `$button['name']` do you not think it's confusing if my code just checks for `$button['Name']`?

**Comment by dorgan** [comment]
@bergware sorry my server was down due to hardware issues, so didnt want to follow up if i couldnt make changes.  Are you OK moving forward with current code, being that `$button['namae']` is the current value assigned to $page, I think having code the then conditionally sets $page to `$button['Name']` is just confusing, but I am open to changes.

**Comment by bergware** [comment]
Please, see my proposal a few posts up.

**Comment by dorgan** [comment]
@bergware thats still just making use of $button['name'] and $button['Name'], where $button['name'] is the current value used today.

**Comment by dorgan** [comment]
guess its silly to knit pick here, updated.

**Comment by bergware** [comment]
Ok, thanks

**Pull request merged**
