### PR TITLE
Change Dashboard Parity status to be invalid and not emulated.

### PR DESCRIPTION
**Pull request by SimonFair**
Please find suggested changes to Dash board view if Parity is invalid or being rebuilt, Currently it says emulated.

Let me know if I should remove multi-lang or add to others and status if you think should be something different to rebuild or invalid.

Made the same change on my 6.9.2 server as its currently rebuilding parity.

image

### CODE REVIEW

**Comment by Squidly271** [comment]
What adding text to the GUI, you should also add the line to https://github.com/unraid/lang-en_US in this case translations.txt and reference this PR

**Comment by bergware** [comment]
To remain consistency with the Main page, the status of the parity disk(s) should be reported as "invalid".

In the latest rc3 the exact parity operation is displayed, so the user knows what is going on.

**Comment by SimonFair** [comment]
> To remain consistency with the Main page, the status of the parity disk(s) should be reported as "invalid".
> 
> In the latest rc3 the exact parity operation is displayed, so the user knows what is going on.
> 
> Ps. regarding translations. I run a code scanner to find new translations and add them to the appropriate text files, no need to worry about that.

Change status to invalid and added Multi language support for other values.

**Comment by bergware** [comment]
You don’t need to translate each individual text item.The translation takes place in the text which is returned at the end.

**Comment by SimonFair** [comment]
> You don’t need to translate each individual text item.The translation takes place in the text which is returned at the end.

Thanks sorry missed that, I have updated to remove _( )

**Comment by bergware** [comment]
Looks good

**Comment by limetech** [comment]
Thank you @SimonFair

**Pull request merged**
