### PR TITLE
SweetAlert bugfixes

### PR DESCRIPTION
**Pull request by gfjardim**

### CODE REVIEW

**Comment by eschultz** [comment]
@gfjardim I haven't tested this code yet but a quick look over the diff reveals a few unicode and newline characters were restored as well?

**Comment by gfjardim** [comment]
Those were introduced by GitHub, I made that commit directly from this site. I'll commit using git instead.

**Comment by eschultz** [comment]
ok, I see, the main fix is nesting the OK button instead of the Cancel button under the `sa-confirm-button-container` div.

**Comment by gfjardim** [comment]
Yes. The other change is the color of animation, green instead of blue.

**Pull request merged**
