### PR TITLE
Prevent text overlapping input boxes on Edit Docker Page

### PR DESCRIPTION
**Pull request by Squidly271**
See here: https://lime-technology.com/forums/topic/56392-support-djoss-dupeguru/?page=2&tab=comments#comment-639931

### CODE REVIEW

**Comment by bergware** [comment]
Where does this overlapping happen?

**Comment by Squidly271** [comment]
Follow the link

**Comment by Squidly271** [comment]
It actually only seems to happen on the black theme, but I couldn't manage to figure out what was wrong with the css on the theme file, so put the css fix in the page instead which doesn't appear to affect any of the other themes.

**Comment by bergware** [comment]
Haha, somebody blaming Eric and me ;)

I think the problem in the first place is the very loooonnnnggg description, make it shorter and the problem is solved, but mayby your solution is more appropriate!

**Pull request merged**
